os: linux
dist: bionic
language: java
before_install:
  # default pandoc is too old -> install a newer version manually
  - PANDOC_VERSION="2.9.2"
  - pandoc_deb="pandoc-${PANDOC_VERSION}-1-amd64.deb"
  - wget "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${pandoc_deb}"
  - sudo dpkg -i ${pandoc_deb}
  - rm ${pandoc_deb}

  # default textlife from apt-get is too old
  # install the latest texlife version manually
  - REMOTE="http://mirror.ctan.org/systems/texlive/tlnet"
  - INSTALL="/tmp/install-texlive"
  - mkdir -p $INSTALL
  - curl -sSL $REMOTE/install-tl-unx.tar.gz | tar -xzv -C $INSTALL --strip-components=1
  - sudo $INSTALL/install-tl -no-gui -profile .texlife.profile
  - VERSION=$($INSTALL/install-tl --version | grep 'version' | grep -o '[0-9]\{4\}')
  - PLATFORM=$($INSTALL/install-tl --print-platform)
  - TEXLIVE_DIR="/usr/local/texlive/${VERSION}"
  - TEXBIN="/usr/local/texlive/${VERSION}/bin/${PLATFORM}"
  - export "PATH=$TEXBIN:$PATH"

  # initialization for tlmgr
  - sudo apt-get install xzdec
  - tlmgr init-usertree

  # install pdftoppm for rendering the PDFs
  - sudo apt-get install poppler-utils

  # for executing python based pandoc filters install python and pip
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install wheel

  # for converting to mobi
  - sudo apt-get install calibre

  # install python filters
  - pip3 install pandoc-latex-environment


  - sudo chown -hR $(whoami) "$TEXLIVE_DIR"
  # packages specified in the template
  - tlmgr install adjustbox background bidi csquotes footmisc footnotebackref fvextra mdframed pagecolor sourcecodepro sourcesanspro titling ulem upquote xurl

  # trial and error
  - tlmgr install letltxmacro zref everypage framed collectbox

  # packages needed for the template
  - tlmgr install xecjk filehook unicode-math ucharcat ly1 mweights mdframed needspace

  # packages needed for the books
  - tlmgr install awesomebox fontawesome5 newunicodechar
script:
  - make -C volume1 all
  - make -C volume1 png
before_deploy: "cd ~"
deploy:
  provider: releases
  api_key:
    secure: "BAXn+qMv1FR0bfpB5pLNJmkN82Xi13CLyOwE/+1Ua3oDO7f3NsPLULowGIZsV6jU8qBlXQPOD7qnE0Ww0VEDvxNtzU/5TymkRboTFcoC3lcSOKf0q6bgN9R8NVBzZaj3jK65+peGOGtaoXOkiqAZF6qQd415iCen5/kIcH+R5EszffaOGfnz0NJsSf39fSHKPB3LvCHAE6n6Y3v8x+NGvWDald0iwVtYMpL9YbcCtXthQRi0+BggRtstvk+97SgRPa1AwaRT5NIzYLESi9Jm/gEYf3QXwmv+qgiK3D3PPh6YGUfTGxu1RpSNK4R4e1F6zbmyYRQR07Z6AHt0lSb0XVtxokT7iMsK5LddEbsE+aNydfztt0r6Gx2TrisF4LqYpT16kJg3hpIIjBEZV9ulqdq0D/oqtP35wyc7yr7ThGgfnyCrjs+14xMzE4HwKEZwWCPltyBiHeqQbILvA3yag6Wp08t/y6/3gtX7jMSUTi6boMoZFB0ziTA/8t99Jmt9xrsvebvgM0SUO+fycZOIqNaHGpEd9fg7Y3dgIi4D/oNyuiELcTyX1f4EV8i9jGaB/ldimujx+l7oh/6ElxHhgLDGghHvrcIZBFvX0RaHTJS7uX482jPtyj+z/zyPWFW2/PtaoBO4gX3LcxTpxdMppDb+YBsbJ+7+xrKzEOWKbEY="
  file_glob: true
  file:
    - file: "volume1/build/**/*.{epub,html.tar.gz,mobi,pdf}"
  skip_cleanup: true
  on:
    tags: true
    repo: theclue/programming-with-haiku
    all_branches: true
